POST {{url}}/api/auth/register
Content-Type: application/json

{
  "login": "user@user.user", "password": "password"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

###

GET {{url}}/api/auth/email-confirm
Content-Type: application/json
Authorization: Bearer

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
###

POST {{url}}/api/auth/reset-password
Content-Type: application/json

{
  "login": "user@user.user"
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST {{url}}/api/auth/login
Content-Type: application/json

{
  "login": "user@user.user", "password": "password"
}

> {%
client.global.set("auth_token", response.body.access_token);
client.global.set("refresh_token", response.body.refresh_token);

client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

POST {{url}}/api/auth/refresh
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "refresh_token": "{{refresh_token}}"
}

> {%
client.global.set("auth_token", response.body.access_token);

client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
