version: "3.9"

networks:
  default:

volumes:
  caddy_data:
  caddy_config:

services:
  web:
    image: ${IMAGE}/web:${VERSION}
    networks:
      - default
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    env_file:
      - .env.ci

  app:
    image: ${IMAGE}/app:${VERSION}
    restart: unless-stopped
    networks:
      - default
    env_file:
      - .env.ci
