GET {{url}}/api/user
Authorization: {{auth_type}} {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###

DELETE {{url}}/api/user
Authorization: {{auth_type}} {{auth_token}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}
