name: "Build"

on:
  workflow_call:

env:
  NODE_VERSION: '16.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])
          echo "IMAGE_NAME=ghcr.io/${IMAGE_NAME}" >> $GITHUB_ENV
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV
          echo "version: ${VERSION}" > docker/caddy/version.txt

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Use Yarn cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: app
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Lint
        working-directory: app
        run: yarn lint

      - name: Test unit
        working-directory: app
        run: yarn test:cov

      - name: Collect code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: app/coverage/lcov-report

      - name: Test e2e
        working-directory: app
        run: yarn test:e2e

      - name: Build
        working-directory: app
        run: | 
          yarn build
          yarn install --prefer-offline --frozen-lockfile --prod

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push app docker image
        uses: docker/build-push-action@v2
        with:
          context: app
          builder: ${{ steps.buildx.outputs.name }}
          push: true # Will only build if this is not here
          tags: |
            ${{ env.IMAGE_NAME }}/app:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push web docker image
        uses: docker/build-push-action@v2
        with:
          context: docker/caddy
          builder: ${{ steps.buildx.outputs.name }}
          push: true # Will only build if this is not here
          tags: |
            ${{ env.IMAGE_NAME }}/web:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}/web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
