name: Deploy to DEV

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs:
      - build
    runs-on: [self-hosted, dev]
    env:
      HOST: api-dev.budget.marcus-rise.dev
    environment:
      name: Development
      url: https://${{ env.HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup image name
        run: |
          IMAGE=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])
          echo "IMAGE=ghcr.io/${IMAGE_NAME}" >> $GITHUB_ENV

      - name: Setup version
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "VERSION=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Setup version
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy
        run: |
          eval "echo \"$(cat .env.ci)\"" > .env
          docker compose pull
          docker compose up -d --force-recreate
