name: Deploy to DEV

on:
  workflow_run:
    workflows: [ "Build" ]
    branches:
      - master
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, dev]
    env:
      HOST: api-dev.budget.marcus-rise.dev
    environment:
      name: Development
      url: https://${{ env.HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup env
        run: |
          IMAGE_NAME=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])
          echo "IMAGE_NAME=ghcr.io/${IMAGE_NAME}" >> $GITHUB_ENV
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy
        run: |
          eval "echo \"$(cat .env.ci)\"" > .env
          cat .env.ci
          docker compose pull
          docker compose up -d --force-recreate
