name: Deploy to DEV

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    uses: ./.github/workflows/build.yml

  deploy:
    needs:
      - build
    runs-on: [self-hosted, dev]
    env:
      HOST: api-dev.budget.marcus-rise.dev
    environment:
      name: Development
      url: https://${{ env.HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup image name
        run: |
          IMAGE=$(echo ${{ github.repository }} | tr [:upper:] [:lower:])
          echo "IMAGE=ghcr.io/${IMAGE}" >> $GITHUB_ENV

      - name: Setup version for PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "VERSION=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Setup version for not PR
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV

      - name: Deploy
        env:
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          ADMINER_USER: ${{ secrets.ADMINER_USER }}
          ADMINER_PASSWORD: ${{ secrets.ADMINER_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          SESSION_TTL: ${{ secrets.SESSION_TTL }}
          TOKEN_TTL: ${{ secrets.TOKEN_TTL }}
          REGISTRATION_EMAIL_TOKEN_TTL: ${{ secrets.REGISTRATION_EMAIL_TOKEN_TTL }}
          RESET_PASSWORD_EMAIL_TOKEN_TTL: ${{ secrets.RESET_PASSWORD_EMAIL_TOKEN_TTL }}
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_LOGIN: ${{ secrets.MAIL_LOGIN }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: ${{ secrets.MAIL_FROM }}
          MAIL_FRONTEND_BASE_URL: ${{ secrets.MAIL_FRONTEND_BASE_URL }}
        run: |
          eval "echo \"$(cat .env.ci)\"" > .env
          docker compose pull
          docker compose up -d --force-recreate
